-- Mandamientos de pago. Solo MP_ESTADO != 3 (no anulados).
-- Filtrado por CART_CODIGO de los comparendos del run.
SELECT
    mp.CART_CODIGO,
    mp.MP_FECHA,
    mp.MP_RESOLUCION,
    mp.NOTIF_FECHA
FROM CARTE_MANDAMIENTO_PAGO mp
INNER JOIN (
    SELECT DISTINCT IM.CART_CODIGO
    FROM MUEVETE.STG_COMPARENDOS_BI STG
    INNER JOIN MUEVETE.VIEW_CONTRA_COMPA_IMPUESTOS IM
           ON IM.COMP_NUMERO = STG.NRO_COMPARENDO
    WHERE IM.TIPO_COMPARENDO = 'SAST'
      AND STG.RUN_ID = ?
      AND IM.CART_CODIGO IS NOT NULL
) sub ON sub.CART_CODIGO = mp.CART_CODIGO
WHERE mp.MP_ESTADO != 3
