-- Seguimientos para FECHA_ACTUACION / RESOLUCION_ACTUACION.
-- Trae todos los seguimientos cuyo COMP_CODIGO este en la base del run.
-- Java luego filtra por (COMP_CODIGO, SEGUI_CODIGO_PASO == COMP_PASO_PROCESO_ACTUAL).
SELECT
    s.COMP_CODIGO,
    s.SEGUI_CODIGO_PASO,
    s.SEGUI_FECHA_RESOL,
    SUBSTR(s.SEGUI_RESOLUCION, 1, 80) AS SEGUI_RESOLUCION
FROM CONTRA_COMPARENDO_SEGUIMIENTO s
INNER JOIN (
    SELECT DISTINCT IM.COMP_CODIGO
    FROM MUEVETE.STG_COMPARENDOS_BI STG
    INNER JOIN MUEVETE.VIEW_CONTRA_COMPA_IMPUESTOS IM
           ON IM.COMP_NUMERO = STG.NRO_COMPARENDO
    WHERE IM.TIPO_COMPARENDO = 'SAST'
      AND STG.RUN_ID = ?
) sub ON sub.COMP_CODIGO = s.COMP_CODIGO
