-- =====================================================================
-- Cartera Turbaco
-- Driving table = MUEVETE.STG_COMPARENDOS_BI filtrado por RUN_ID (mismo
-- patron que recaudo_interno.sql / recaudo_externo.sql, plan estable).
-- Parametro :runId -> UUID del run actual.
-- =====================================================================
SELECT /*+ LEADING(STG) USE_NL(IM) USE_NL(seg) USE_NL(seg2) USE_NL(mp) USE_NL(proc) FIRST_ROWS(100) */
     IM.COMP_NUMERO COMP_NUMERO,
     IM.COMP_FECHA COMP_FECHA,
     IM.TIPO_COMPARENDO TIPO_COMPARENDO,
     IM.CART_VALOR_INICIAL CART_VALOR_INICIAL,
     SUBSTR(IM.COMP_ESTADO, 1, 80) COMP_ESTADO,
     IM.COMP_CODIGO COMP_CODIGO,
     SUBSTR(IM.TIPO_INFRACTOR, 1, 80) TIPO_INFRACTOR,
     SUBSTR(IM.PER_TIPO_DOCUMENTO, 1, 80) PER_TIPO_DOCUMENTO,
     IM.PER_NRO_IDENTIFICACION PER_NRO_IDENTIFICACION,
     IM.PER_NOMBRES PER_NOMBRES,
     SUBSTR(IM.PER_DIRECCION_INFRACTOR, 1, 80) PER_DIRECCION_INFRACTOR,
     IM.PER_EMAIL_INFRACTOR PER_EMAIL_INFRACTOR,
     IM.PER_TELEFONO_INFRACTOR PER_TELEFONO_INFRACTOR,
     IM.VEHI_PLACA VEHI_PLACA,
     IM.INFR_CODIGO_VISISBLE INFR_CODIGO_VISISBLE,
     proc.PROC_PASO_DESCRIPCION PROCESO_ESTADO,
     seg.SEGUI_FECHA_RESOL FECHA_ACTUACION,
     SUBSTR(seg.SEGUI_RESOLUCION, 1, 80) RESOLUCION_ACTUACION,
     seg2.SEGUI_FECHA_RESOL FECHA_SANCION,
     SUBSTR(seg2.SEGUI_RESOLUCION, 1, 80) RESOLUCION_SANCION,
     mp.MP_FECHA,
     mp.MP_RESOLUCION,
     mp.NOTIF_FECHA MP_NOTIF_FECHA
FROM MUEVETE.STG_COMPARENDOS_BI STG
INNER JOIN MUEVETE.VIEW_CONTRA_COMPA_IMPUESTOS IM
       ON IM.COMP_NUMERO = STG.NRO_COMPARENDO
LEFT JOIN CONTRA_COMPARENDO_SEGUIMIENTO seg
       ON seg.COMP_CODIGO = IM.COMP_CODIGO
      AND seg.SEGUI_CODIGO_PASO = IM.COMP_PASO_PROCESO_ACTUAL
LEFT JOIN CONTRA_COMPARENDO_SEGUIMIENTO seg2
       ON seg2.COMP_CODIGO = IM.COMP_CODIGO
      AND seg2.SEGUI_CODIGO_PASO = 5
      AND seg2.SEGUI_ESTADO = 1
LEFT JOIN CARTE_MANDAMIENTO_PAGO mp
       ON mp.CART_CODIGO = IM.CART_CODIGO
      AND mp.MP_ESTADO != 3
LEFT JOIN CONTRA_PROC_PASO_DESCRIPCION proc
       ON proc.PROC_PASO_CODIGO = IM.COMP_PASO_PROCESO_ACTUAL
WHERE IM.TIPO_COMPARENDO = 'SAST' AND STG.RUN_ID = ?
