-- Base de cartera: STG x VIEW_CONTRA_COMPA_IMPUESTOS, sin LEFT JOINs.
-- Devuelve los datos principales + las FK que necesitamos para enriquecer despues
-- en queries separadas (proc, seg actuacion, seg sancion, mp).
SELECT
    IM.COMP_NUMERO,
    IM.COMP_FECHA,
    IM.TIPO_COMPARENDO,
    IM.CART_VALOR_INICIAL,
    SUBSTR(IM.COMP_ESTADO, 1, 80) AS COMP_ESTADO,
    IM.COMP_CODIGO,
    SUBSTR(IM.TIPO_INFRACTOR, 1, 80) AS TIPO_INFRACTOR,
    SUBSTR(IM.PER_TIPO_DOCUMENTO, 1, 80) AS PER_TIPO_DOCUMENTO,
    IM.PER_NRO_IDENTIFICACION,
    IM.PER_NOMBRES,
    SUBSTR(IM.PER_DIRECCION_INFRACTOR, 1, 80) AS PER_DIRECCION_INFRACTOR,
    IM.PER_EMAIL_INFRACTOR,
    IM.PER_TELEFONO_INFRACTOR,
    IM.VEHI_PLACA,
    IM.INFR_CODIGO_VISISBLE,
    IM.COMP_PASO_PROCESO_ACTUAL,
    IM.CART_CODIGO
FROM MUEVETE.STG_COMPARENDOS_BI STG
INNER JOIN MUEVETE.VIEW_CONTRA_COMPA_IMPUESTOS IM
       ON IM.COMP_NUMERO = STG.NRO_COMPARENDO
WHERE IM.TIPO_COMPARENDO = 'SAST'
  AND STG.RUN_ID = ?
