-- =====================================================================
-- Recaudo Interno Turbaco
-- Adaptada para filtrar por lista de comparendos via tabla staging.
-- Parametro :runId  -> UUID del run actual
-- =====================================================================
SELECT FUENTE, TIPO_CARTERA, FECHA_PAGO, RECIBO, VALOR_RECIBO, TIPO_DOCUMENTO, IDENTIFICACION, NOMBRE, VEHI_PLACA, COMP_NUMERO, COMP_FECHA, ANIO_COMPARENDO, PRESCRIPCION, TIPO_COMPARENDO, CLASE_VEHICULO, TIPO, SERVICIO_VEHICULO, VALOR_PAGADO, DISTRI_FECHA, RESOLUCION_MP, CART_VALOR_INICIAL, CONCEPTO, ESTADO_CARTERA, CONCEPTO_PRINCIPAL, GESTION, PORC_DESCUENTO, DESCUENTO_CARTERA, DESCUENTO_INTERESES, CANT_DESCUENTO_CARTERA, CANT_DESCUENTO_INTERESES, SEGUI_RESOLUCION, SEGUI_FECHA_RESOL, VALOR_INTERES
FROM (
WITH MP AS(
SELECT
MP.CART_CODIGO,
MP.MP_CODIGO,
MP.MP_RESOLUCION,
MP.MP_FECHA, CAR.CART_NRO_REFERENCIA,
CAR.CART_FECHA,
MPD.CART_RESOL
FROM
CARTE_MANDAMIENTO_PAGO MP
INNER JOIN CARTE_MP_DETALLE MPD ON MPD.MP_CODIGO = MP.MP_CODIGO
LEFT JOIN CARTE_CARTERA CAR ON CAR.CART_CODIGO = MPD.CART_CODIGO
WHERE CAR.TIPOCAR_CODIGO = 1
AND MP.MP_ESTADO NOT IN (2,3)
)
SELECT
'RECAUDO INTERNO OT ' FUENTE,
1 TIPO_CARTERA,
TO_DATE(MC.MOVCJ_FECHA) FECHA_PAGO,
TO_CHAR(MC.MOVCJ_CODIGO) RECIBO,
MC.MOVCJ_VALOR VALOR_RECIBO,
MC.TIPO_DOCUMENTO TIPO_DOCUMENTO,
MC.PER_NRO_IDENTIFICACION IDENTIFICACION,
MC.NOMBRE_TITULAR NOMBRE,
COMP.VEHI_PLACA,
COMP.COMP_NUMERO,
COMP.COMP_FECHA,
TO_CHAR(COMP.COMP_FECHA,'YYYY') ANIO_COMPARENDO,
CASE WHEN TO_CHAR(COMP.COMP_FECHA,'YYYY') < '2014' THEN 'PRESCRITO' ELSE 'NO PRESCRITO' END PRESCRIPCION,
CASE WHEN COMP.PROC_CODIGO=2 AND COMP.COMP_POLCA =0 THEN '2.LOCALES'
WHEN COMP.PROC_CODIGO=2 AND COMP.COMP_POLCA = 1 THEN '1.DITRA'
WHEN COMP.PROC_CODIGO=1 AND COMP.COMP_POLCA =0 THEN '2.LOCALES'
WHEN COMP.PROC_CODIGO=1 AND COMP.COMP_POLCA = 1 THEN '1.DITRA'
WHEN COMP.PROC_CODIGO=3 THEN '3.SAST'
ELSE '4.ACUERDOS DE PAGO' END TIPO_COMPARENDO,
ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) CLASE_VEHICULO,
CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN('MICROBUS','MAQUINARIA INDUSTRIAL','MINICARGADOR','BUSETA','CAMPERO','GRUA','CAMION','MONTACARGAS','VIBROCOMPACTADORA','MOTONIVELADORA','COSECHADORA','CAMIONETA','VOLQUETA','EXCAVADORA','TRACTOR','FRESADORA','AUTOMOVIL','TRACTOCAMION','SEMIREMOLQUE','TRITURADORA','DUMPER (VOLQUETA ARTICULADA)','BUS','BULDOZER','RETROEXCAVADORA','COMPACTADORA','TRACCION ANIMAL','MAQUINARIA AGRICOLA')  THEN 'DIFERENTE A MOTOCICLETA' ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN ('','SIN CLASE') THEN CASE WHEN (REGEXP_LIKE(COMP.VEHI_PLACA,'^[0-9]{3}[A-Za-z]{3}$') OR REGEXP_LIKE(COMP.VEHI_PLACA,'^[A-Za-z]{3}(0[1-9]|[1-9][0-9])[A-Za-z]?$')) THEN 'MOTOCICLETA' ELSE 'DIFERENTE A MOTOCICLETA' END ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN ('MOTOTRICICLO','BICICLETA','MOTOCICLETA','MOTOCARRO','CUATRIMOTO')  THEN 'MOTOCICLETA' ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IS  NULL THEN 'DIFERENTE A MOTOCICLETA' ELSE 'DIFERENTE A MOTOCICLETA' END END END END TIPO,
ADMIN_DESC_PARAMETRO(32,COMP.VEHI_SERVICIO) SERVICIO_VEHICULO,
SUM(REC.DISTRI_VALOR) VALOR_PAGADO,
REC.DISTRI_FECHA,
MP.MP_RESOLUCION RESOLUCION_MP,
CAR.CART_VALOR_INICIAL,
CASE WHEN MP.MP_CODIGO IS NOT NULL THEN 'Mandamiento de Pago' WHEN CR.RECIB_FECHA IS NOT NULL THEN 'Persuasivo' WHEN SEG.SEGUI_RESOLUCION IS NOT NULL THEN 'Resolucion' ELSE 'Vigente' END CONCEPTO,
CCC.CONCAR_NOMBRE ESTADO_CARTERA,
CCC.CONCAR_NOMBRE CONCEPTO_PRINCIPAL,
CASE WHEN (MP.MP_CODIGO IS NOT NULL OR CR.RECIB_FECHA IS NOT NULL) THEN 'CARTERA COACTIVO' ELSE 'CARTERA VIGENTE' END GESTION,
CASE WHEN VPD.DESC_CODIGO IS NOT NULL THEN VPD.DESC_PORCENTAJE||'%' WHEN VP.PAGO_PARCIAL = 1 THEN 'Abono' ELSE 'N/A' END PORC_DESCUENTO,
VPD.DESC_VALOR_DESCUENTO DESCUENTO_CARTERA,
RDV.VD_VALOR_UNIT * (-1) DESCUENTO_INTERESES,
CASE WHEN VPD.DESC_VALOR_DESCUENTO IS NOT NULL THEN 1 ELSE 0 END CANT_DESCUENTO_CARTERA,
CASE WHEN RDV.VD_VALOR_UNIT IS NOT NULL THEN 1 ELSE 0 END CANT_DESCUENTO_INTERESES,
SEG.SEGUI_RESOLUCION SEGUI_RESOLUCION,
SEG.SEGUI_FECHA_RESOL SEGUI_FECHA_RESOL,
RDV2.VD_VALOR_UNIT VALOR_INTERES
FROM RECAU_DISTRIBUCION_DETALLADO REC
LEFT JOIN CARTE_CARTERA CAR  ON REC.CART_CODIGO = CAR.CART_CODIGO
INNER JOIN CONTRA_COMPARENDO COMP ON COMP.CART_CODIGO = CAR.CART_CODIGO  AND COMP.ROWID IN (SELECT MAX(ROWID) FROM CONTRA_COMPARENDO WHERE CART_CODIGO = CAR.CART_CODIGO AND comp_estado!=2 GROUP BY COMP_NUMERO)
INNER JOIN MUEVETE.STG_COMPARENDOS_BI STG ON STG.NRO_COMPARENDO = COMP.COMP_NUMERO AND STG.RUN_ID = ?
LEFT JOIN CONTRA_COMPARENDO_SEGUIMIENTO SEG ON SEG.COMP_CODIGO = COMP.COMP_CODIGO AND SEG.SEGUI_CODIGO_PASO = 5 AND SEG.SEGUI_ESTADO = 1 AND SEG.ROWID IN (SELECT MAX(ROWID) FROM CONTRA_COMPARENDO_SEGUIMIENTO where SEGUI_CODIGO_PASO = 5 AND SEGUI_ESTADO = 1 GROUP BY COMP_CODIGO)
LEFT JOIN COACT_CART_RECIB_DETALLE CRD ON CRD.CART_CODIGO = REC.CART_CODIGO AND CRD.ROWID IN (SELECT MAX(ROWID) FROM COACT_CART_RECIB_DETALLE GROUP BY CART_CODIGO )
LEFT JOIN COACT_CARTERA_RECIBIDA CR ON CR.RECIB_CODIGO = CRD.RECIB_CODIGO
LEFT JOIN MP ON MP.CART_CODIGO = REC.CART_CODIGO
left JOIN VIEW_RECAU_MOVCAJA_CONSULTA MC ON MC.MOVCJ_CODIGO = REC.MOVCJ_CODIGO
LEFT JOIN CARTE_CONCEPTOS_CARTERA CCC ON CCC.CONCAR_CODIGO = REC.CONCAR_CODIGO
LEFT JOIN RECAU_VP_DESCUENTO VPD ON VPD.VP_CODIGO = MC.VP_CODIGO AND VPD.CART_CODIGO = REC.CART_CODIGO AND VPD.CONCAR_CODIGO IN (328, 308)
LEFT JOIN RECAU_VOLANTE_PAGO VP ON VP.VP_CODIGO = MC.VP_CODIGO
LEFT JOIN VIEW_RECAU_DETALLE_VOLANTE RDV ON RDV.VP_CODIGO = MC.VP_CODIGO AND RDV.CART_CODIGO = REC.CART_CODIGO AND RDV.CONCAR_CODIGO_SUB IN (436)
LEFT JOIN VIEW_RECAU_DETALLE_VOLANTE RDV2 ON RDV2.VP_CODIGO = MC.VP_CODIGO AND RDV2.CART_CODIGO = REC.CART_CODIGO AND RDV2.CONCAR_CODIGO_SUB = REC.CONCAR_CODIGO AND RDV2.CONCAR_CODIGO_SUB IN (318,411,409,410,407,408)
WHERE REC.CONCAR_CODIGO IN (348,411,351,352,409,410,130,131,407,408)
AND COMP.PROC_CODIGO = 3
GROUP BY
'RECAUDO INTERNO OT',
TO_DATE(MC.MOVCJ_FECHA) ,
TO_CHAR(MC.MOVCJ_CODIGO) ,
MC.MOVCJ_VALOR ,
MC.TIPO_DOCUMENTO ,
MC.PER_NRO_IDENTIFICACION ,
MC.NOMBRE_TITULAR ,
COMP.VEHI_PLACA,
COMP.COMP_NUMERO,
COMP.COMP_FECHA,
CASE WHEN COMP.PROC_CODIGO=2 AND COMP.COMP_POLCA =0 THEN '2.LOCALES'
WHEN COMP.PROC_CODIGO=2 AND COMP.COMP_POLCA = 1 THEN '1.DITRA'
WHEN COMP.PROC_CODIGO=1 AND COMP.COMP_POLCA =0 THEN '2.LOCALES'
WHEN COMP.PROC_CODIGO=1 AND COMP.COMP_POLCA = 1 THEN '1.DITRA'
WHEN COMP.PROC_CODIGO=3 THEN '3.SAST'
ELSE '4.ACUERDOS DE PAGO' END,
ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) ,
CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN ('MOTOCICLETA', 'BICICLETA', 'MOTOCARRO', 'MOTOTRICICLO', 'CUATRIMOTO', 'CUADRICICLO', 'CICLOMOTOR') THEN 'MOTOCICLETA' WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) NOT IN ('MOTOCICLETA', 'BICICLETA', 'MOTOCARRO', 'MOTOTRICICLO', 'CUATRIMOTO', 'CUADRICICLO', 'CICLOMOTOR') AND COMP.VEHI_CLASE IS NOT NULL THEN 'DIFERENTE A MOTO' ELSE 'SIN_IDENTIFICAR' END,
ADMIN_DESC_PARAMETRO(32,COMP.VEHI_SERVICIO) ,
REC.DISTRI_FECHA,
MP.MP_RESOLUCION ,
CAR.CART_VALOR_INICIAL,
CAR.CART_INTERESES,
CASE WHEN MP.MP_CODIGO IS NOT NULL THEN 'Mandamiento de Pago' WHEN CR.RECIB_FECHA IS NOT NULL THEN 'Persuasivo' WHEN SEG.SEGUI_RESOLUCION IS NOT NULL THEN 'Resolucion' ELSE 'Vigente' END,
CASE WHEN (MP.MP_CODIGO IS NOT NULL OR CR.RECIB_FECHA IS NOT NULL) THEN 'CARTERA COACTIVO' ELSE 'CARTERA VIGENTE' END,
MC.CONCAR_NOMBRE ,
CCC.CONCAR_NOMBRE,
CASE WHEN VPD.DESC_CODIGO IS NOT NULL THEN VPD.DESC_PORCENTAJE||'%' WHEN VP.PAGO_PARCIAL = 1 THEN 'Abono' ELSE 'N/A' END,
VPD.DESC_VALOR_DESCUENTO ,
RDV.VD_VALOR_UNIT,
SEG.SEGUI_RESOLUCION,
SEG.SEGUI_FECHA_RESOL,
RDV2.VD_VALOR_UNIT
) CONSULTA
