-- =====================================================================
-- Recaudo Externo Turbaco
-- Adaptada para filtrar por lista de comparendos via tabla staging.
-- Parametro :runId  -> UUID del run actual
-- =====================================================================
WITH MP AS(
SELECT
MP.CART_CODIGO,
MP.MP_CODIGO,
MP.MP_RESOLUCION,
MP.MP_FECHA, CAR.CART_NRO_REFERENCIA,
CAR.CART_FECHA,
MPD.CART_RESOL
FROM
CARTE_MANDAMIENTO_PAGO MP
INNER JOIN CARTE_MP_DETALLE MPD ON MPD.MP_CODIGO = MP.MP_CODIGO
LEFT JOIN CARTE_CARTERA CAR ON CAR.CART_CODIGO = MPD.CART_CODIGO
WHERE CAR.TIPOCAR_CODIGO = 1
AND MP.MP_ESTADO NOT IN (2,3)
)
SELECT DISTINCT
'RECAUDO EXTERNO' FUENTE,
1 TIPO_CARTERA,
TO_DATE(tempo.rec_fecha_aplica) FECHA_PAGO,
tempo.rec_num_recaudo RECIBO,
tempo.rec_total VALOR_RECIBO,
admin_desc_parametro(1, per.PER_TIPO_IDENTIFICACION) TIPO_DOCUMENTO,
NVL(per.per_nro_identificacion,TEMPO.REC_IDENTIFICACION) IDENTIFICACION,
per.per_nombres || ' ' || per.per_apellidos NOMBRE,
tempo.rec_placa VEHI_PLACA,
tempo.rec_com_numero COMP_NUMERO,
tempo.rec_com_fecha COMP_FECHA,
to_char(tempo.rec_com_fecha, 'YYYY') ANIO_COMPARENDO,
CASE WHEN TO_CHAR(tempo.rec_com_fecha,'YYYY') < '2014' THEN 'PRESCRITO' ELSE 'NO PRESCRITO' END PRESCRIPCION,
CASE WHEN tempo.rec_polca='N' AND tempo.rec_FOTOMULTA='N' THEN 'LOCALES'
WHEN tempo.rec_polca='S' THEN 'DITRA'
WHEN tempo.rec_FOTOMULTA='S' THEN 'SAST'
ELSE 'NO IDENTIFICADO' END TIPO_COMPARENDO,
ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) CLASE_VEHICULO,
CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN('MICROBUS','MAQUINARIA INDUSTRIAL','MINICARGADOR','BUSETA','CAMPERO','GRUA','CAMION','MONTACARGAS','VIBROCOMPACTADORA','MOTONIVELADORA','COSECHADORA','CAMIONETA','VOLQUETA','EXCAVADORA','TRACTOR','FRESADORA','AUTOMOVIL','TRACTOCAMION','SEMIREMOLQUE','TRITURADORA','DUMPER (VOLQUETA ARTICULADA)','BUS','BULDOZER','RETROEXCAVADORA','COMPACTADORA','TRACCION ANIMAL','MAQUINARIA AGRICOLA')  THEN 'DIFERENTE A MOTOCICLETA' ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN ('','SIN CLASE') THEN CASE WHEN (REGEXP_LIKE(COMP.VEHI_PLACA,'^[0-9]{3}[A-Za-z]{3}$') OR REGEXP_LIKE(COMP.VEHI_PLACA,'^[A-Za-z]{3}(0[1-9]|[1-9][0-9])[A-Za-z]?$')) THEN 'MOTOCICLETA' ELSE 'DIFERENTE A MOTOCICLETA' END ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IN ('MOTOTRICICLO','BICICLETA','MOTOCICLETA','MOTOCARRO','CUATRIMOTO')  THEN 'MOTOCICLETA' ELSE CASE WHEN ADMIN_DESC_PARAMETRO(31,COMP.VEHI_CLASE) IS  NULL THEN 'DIFERENTE A MOTOCICLETA' ELSE 'DIFERENTE A MOTOCICLETA' END END END END TIPO,
ADMIN_DESC_PARAMETRO(32,COMP.VEHI_SERVICIO) SERVICIO_VEHICULO,
tempo.rec_total VALOR_PAGADO,
TO_DATE(TEMPO.rec_fecha_aplica) DISTRI_FECHA,
MP.MP_RESOLUCION RESOLUCION_MP,
((nvl(car.cart_valor_inicial,0) - tempo.rec_total) + tempo.rec_total) CART_VALOR_INICIAL,
CASE WHEN MP.MP_CODIGO IS NOT NULL THEN 'Mandamiento de Pago' WHEN CR.RECIB_FECHA IS NOT NULL THEN 'Persuasivo' WHEN SEG.SEGUI_RESOLUCION IS NOT NULL THEN 'Resolucion' ELSE 'Vigente' END CONCEPTO,
'' ESTADO_CARTERA,
'' CONCEPTO_PRINCIPAL,
CASE WHEN (MP.MP_CODIGO IS NOT NULL OR CR.RECIB_FECHA IS NOT NULL) THEN 'CARTERA COACTIVO' ELSE 'CARTERA VIGENTE' END GESTION,
'' PORC_DESCUENTO,
case when tempo.rec_total < nvl(car.cart_valor_inicial,0) then ((nvl(car.cart_valor_inicial,0) - tempo.rec_total)) else 0 end DESCUENTO_CARTERA,
0 DESCUENTO_INTERESES,
case when tempo.rec_total < nvl(car.cart_valor_inicial,0) then 1 else 0 end CANT_DESCUENTO_CARTERA,
0 CANT_DESCUENTO_INTERESES,
SEG.SEGUI_RESOLUCION,
SEG.SEGUI_FECHA_RESOL,
case when car.cart_valor_inicial is not null and tempo.rec_total > car.cart_valor_inicial then tempo.rec_total - car.cart_valor_inicial else 0 end valor_interes
from RECAU_RECUADO_EXTERNO_WS TEMPO
INNER JOIN MUEVETE.STG_COMPARENDOS_BI STG ON STG.NRO_COMPARENDO = TEMPO.REC_COM_NUMERO AND STG.RUN_ID = ?
INNER JOIN CONTRA_COMPARENDO comp ON comp.comp_numero=tempo.REC_COM_NUMERO AND COMP.ROWID IN (SELECT MAX(ROWID) FROM CONTRA_COMPARENDO WHERE comp_estado!=2 GROUP BY COMP_NUMERO)
LEFT JOIN CONTRA_COMPARENDO_SEGUIMIENTO SEG ON SEG.COMP_CODIGO = COMP.COMP_CODIGO AND SEG.SEGUI_CODIGO_PASO = 5 AND SEG.SEGUI_ESTADO = 1 AND SEG.ROWID IN (SELECT MAX(ROWID) FROM CONTRA_COMPARENDO_SEGUIMIENTO where SEGUI_CODIGO_PASO = 5 AND SEGUI_ESTADO = 1 GROUP BY COMP_CODIGO)
left join carte_cartera car on car.cart_codigo = comp.cart_codigo
left join admin_personas per on per.per_codigo = car.per_codigo
LEFT JOIN COACT_CART_RECIB_DETALLE CRD ON CRD.CART_CODIGO = car.CART_CODIGO AND CRD.ROWID IN (SELECT MAX(ROWID) FROM COACT_CART_RECIB_DETALLE GROUP BY CART_CODIGO )
LEFT JOIN COACT_CARTERA_RECIBIDA CR ON CR.RECIB_CODIGO = CRD.RECIB_CODIGO
LEFT JOIN MP ON MP.CART_CODIGO = car.CART_CODIGO
WHERE COMP.PROC_CODIGO = 3
